download-image: Replace release with channel
Signed-off-by: Juerg Haefliger <juergh@canonical.com>

diff --git a/bin/download-image b/bin/download-image
--- a/bin/download-image
+++ b/bin/download-image
@@ -32,7 +32,7 @@ function download_image()
 
 function download_ubuntu_classic()
 {
-	local series=${1} flavor=${2} arch=${3} release=${4}
+	local series=${1} flavor=${2} arch=${3} channel=${4}
 	local path raspi url remote_image image_pattern href image
 
 	path=
@@ -45,7 +45,7 @@ function download_ubuntu_classic()
 		raspi=raspi3
 	fi
 
-	case "${release}" in
+	case "${channel}" in
 		""|devel)
 			url=http://cdimage.ubuntu.com/${path}/daily-preinstalled/current/
 			remote_image=${series}-preinstalled-${flavor}-${arch}+${raspi}.img.xz
@@ -69,7 +69,7 @@ function download_ubuntu_classic()
 			fi
 			;;
 		*)
-			echo "-- Error: Invalid release: ${release}" >&2
+			echo "-- Error: Invalid channel: ${channel}" >&2
 			exit 1
 			;;
 	esac
@@ -78,7 +78,7 @@ function download_ubuntu_classic()
 
 	# Download the image
 	if ! download_image "${url}/${remote_image}" "${image}" ; then
-		case "${release}" in
+		case "${channel}" in
 			""|devel)
 				download_ubuntu_classic "${series}" "${flavor}" "${arch}" daily
 				;;
@@ -94,11 +94,11 @@ function download_ubuntu_classic()
 
 function download_ubuntu_core()
 {
-	local series=${1} arch=${2} release=${3}
+	local series=${1} arch=${2} channel=${3}
 	local year url raspi remote_image image
 
 	year=${series#core}
-	case "${release}" in
+	case "${channel}" in
 		""|edge)
 			url=http://cdimage.ubuntu.com/ubuntu-core/${year}/dangerous-edge/pending/
 			;;
@@ -109,7 +109,7 @@ function download_ubuntu_core()
 			url=http://cdimage.ubuntu.com/ubuntu-core/${year}/stable/current/
 			;;
 		*)
-			echo "-- Error: Invalid release: ${release}" >&2
+			echo "-- Error: Invalid channel: ${channel}" >&2
 			exit 1
 			;;
 	esac
@@ -119,7 +119,7 @@ function download_ubuntu_core()
 		raspi=raspi3
 	fi
 	remote_image=ubuntu-core-${year}-${arch}+${raspi}.img.xz
-	image=ubuntu-${release}-${arch}+raspi.img.xz
+	image=ubuntu-${channel}-${arch}+raspi.img.xz
 
 	# Donwload the image
 	download_image "${url}/${remote_image}" "${image}"
@@ -153,7 +153,7 @@ function download_raspios()
 function usage()
 {
 	cat <<EOF
-Usage: download-image [-h] [-r RELEASE] SERIES ARCH
+Usage: download-image [-h] [-c CHANNEL] SERIES ARCH
 
 Download a Raspberry Pi image.
 
@@ -163,9 +163,9 @@ Positional argument:
 
 Optional arguments:
   -h, --help             Show this help text and exit.
-  -r, --release RELEASE  Download release RELEASE of the image. See below for
-                         the list of available releases. If not provided,
-                         defaults to the first release of the list.
+  -c, --channel CHANNEL  Download the image from channel CHANNEL. See below for
+                         the list of available channels. If not provided,
+                         defaults to the first channel of the list.
 
 Image series:
   Ubuntu Desktop:          groovy-desktop, hirsute-desktop, ...
@@ -174,7 +174,7 @@ Image series:
   Raspberry Pi OS Lite:    raspios
   Raspberry Pi OS Desktop: raspios-desktop
 
-Image releases:
+Image channels:
   Ubuntu Desktop:          daily, release
   Ubuntu Classic:          daily, release
   Ubuntu Core:             edge, beta, stable
@@ -183,7 +183,7 @@ Image releases:
 EOF
 }
 
-release=
+channel=
 series=
 arch=
 
@@ -193,9 +193,9 @@ while [ $# -gt 0 ] ; do
 			usage
 			exit
 			;;
-		-r|--release)
+		-c|--channel)
 			shift
-			release=${1}
+			channel=${1}
 			;;
 		*)
 			if [ -z "${series}" ] ; then
@@ -227,7 +227,7 @@ case "${series}" in
 
 	# Ubuntu Classic
 	bionic|focal|groovy|hirsute|impish)
-		download_ubuntu_classic "${series}" server "${arch}" "${release}"
+		download_ubuntu_classic "${series}" server "${arch}" "${channel}"
 		;;
 
 	# Ubuntu Desktop
@@ -236,12 +236,12 @@ case "${series}" in
 			echo "-- Error: Desktop images are only supported on arm64" >&2
 			exit 1
 		fi
-		download_ubuntu_classic "${series%-desktop}" desktop arm64 "${release}"
+		download_ubuntu_classic "${series%-desktop}" desktop arm64 "${channel}"
 		;;
 
 	# Ubuntu Core
 	core18|core20)
-		download_ubuntu_core "${series}" "${arch}" "${release}"
+		download_ubuntu_core "${series}" "${arch}" "${channel}"
 		;;
 
 	# Raspberry Pi OS
