Prefix errors with '** Error: '
Signed-off-by: Juerg Haefliger <juergh@canonical.com>

diff --git a/bin/import-firmware b/bin/import-firmware
--- a/bin/import-firmware
+++ b/bin/import-firmware
@@ -18,7 +18,7 @@ function out()
 	fi
 
 	if [ "${rc}" -ne 0 ] ; then
-		echo "Script failed" >&2
+		echo "** Error: Script failed" >&2
 	fi
 }
 
@@ -71,7 +71,7 @@ while [ "${#}" -gt 0 ] ; do
 			if [ -z "${image}" ] ; then
 				image=${1}
 			else
-				echo "-- Invalid argument: ${1}" >&2
+				echo "** Error: Invalid argument: ${1}" >&2
 				exit 2
 			fi
 			;;
@@ -85,7 +85,7 @@ if [ -z "${image}" ] ; then
 fi
 
 if ! [ -d firmware ] ; then
-	echo "-- No such directory: ./firmware" >&2
+	echo "** Error: No such directory: ./firmware" >&2
 	exit 2
 fi
 
diff --git a/bin/rpi-config b/bin/rpi-config
--- a/bin/rpi-config
+++ b/bin/rpi-config
@@ -8,7 +8,7 @@ function out()
         rc=$?
 
         if [ "${rc}" -ne 0 ] ; then
-                echo "-- Script failed" >&2
+                echo "** Error: Script failed" >&2
         fi
 }
 
@@ -222,7 +222,7 @@ while [ "${#}" -gt 0 ] ; do
 			ROOT_DIR=${1}
 			;;
 		*)
-			echo "-- Invalid argument: ${1}" >&2
+			echo "** Error: Invalid argument: ${1}" >&2
 			exit 2
 			;;
 	esac
@@ -236,7 +236,7 @@ if [ -d "${ROOT_DIR}"/boot/firmware ] ; then
 elif  [ -d "${ROOT_DIR}"/boot ] ; then
 	BOOT_DIR=${ROOT_DIR}/boot
 else
-	echo "-- No such boot directories: ${ROOT_DIR}/boot{/firmware,}" >&2
+	echo "** Error: No such boot directory: ${ROOT_DIR}/boot{/firmware,}" >&2
 	exit 1
 fi
 
diff --git a/bin/rpi-download b/bin/rpi-download
--- a/bin/rpi-download
+++ b/bin/rpi-download
@@ -8,7 +8,7 @@ function out()
 	local rc=${?}
 
 	if [ "${rc}" -ne 0 ] ; then
-		echo "Script failed" >&2
+		echo "** Error: Script failed" >&2
 	fi
 }
 
@@ -83,7 +83,7 @@ while [ $# -gt 0 ] ; do
 			elif [ -z "${arch}" ] ; then
 				arch=${1}
 			else
-				echo "Invalid argument: ${1}" >&2
+				echo "** Error: Invalid argument: ${1}" >&2
 				exit 2
 			fi
 			;;
@@ -97,7 +97,7 @@ if [ -z "${series}" ] || [ -z "${arch}" ] ; then
 fi
 
 if [ "${arch}" != "armhf" ] && [ "${arch}" != "arm64" ] ; then
-	echo "Invalid architecture: ${arch}" >&2
+	echo "** Error: Invalid architecture: ${arch}" >&2
 	exit 1
 fi
 
@@ -174,7 +174,7 @@ case "${series}" in
 
 	*)
 		trap - EXIT INT TERM HUP
-		echo "Invalid series: ${series}" >&2
+		echo "** Error: Invalid series: ${series}" >&2
 		exit 1
 		;;
 
diff --git a/bin/rpi-hostname b/bin/rpi-hostname
--- a/bin/rpi-hostname
+++ b/bin/rpi-hostname
@@ -47,7 +47,7 @@ while [ $# -ne 0 ] ; do
 			action=${1}
 			;;
 		*)
-			echo "Invalid argument: ${1}" >&2
+			echo "** Error: Invalid argument: ${1}" >&2
 			exit 2
 			;;
 	esac
@@ -80,7 +80,7 @@ EOF
 		;;
 	unset)
 		if ! [ -e /etc/hostname.rpi ] ; then
-			echo "Unable to unset hostname" \
+			echo "** Error: Unable to unset hostname" \
 				 "(no such file: /etc/hostname.rpi)" >&2
 			exit 1
 		fi
diff --git a/bin/rpi-install b/bin/rpi-install
--- a/bin/rpi-install
+++ b/bin/rpi-install
@@ -8,7 +8,7 @@ out()
 	rc=$?
 
 	if [ "${rc}" -ne 0 ] ; then
-		echo "-- Script failed" >&2
+		echo "** Error: Script failed" >&2
 	fi
 }
 
@@ -52,14 +52,14 @@ while [ "${#}" -gt 0 ] ; do
 			reboot=1
 			;;
 		-*)
-			echo "-- Invalid argument: ${1}" >&2
+			echo "** Error: Invalid argument: ${1}" >&2
 			exit 1
 			;;
 		*)
 			if [ -z "${installer}" ] ; then
 				installer=${1}
 			else
-				echo "-- Invalid argument: ${1}" >&2
+				echo "** Error: Invalid argument: ${1}" >&2
 				exit 1
 			fi
 			;;
@@ -78,7 +78,7 @@ fi
 
 # Verify the boot directory
 if ! [ -e "${boot_dir}"/config.txt ] ; then
-	echo "-- Invalid boot directory: ${boot_dir}" >&2
+	echo "** Error: Invalid boot directory: ${boot_dir}" >&2
 	exit 1
 fi
 echo "-- Use boot directory ${boot_dir}"
@@ -93,7 +93,7 @@ fi
 if [ -n "${installer}" ] ; then
 	# Check if the provided installer file exists
 	if ! [ -e "${installer}" ] ; then
-		echo "-- No such installer: ${installer}" >&2
+		echo "** Error: No such installer: ${installer}" >&2
 		exit 1
 	fi
 
@@ -107,7 +107,7 @@ else
 	# Check if the remote installer exists
 	installer_url=${github_url}/raw/main/release/rpi-install.tgz
 	if ! wget -q --spider "${installer_url}" ; then
-		echo "-- No such remote installer: ${installer_url}" >&2
+		echo "** Error: No such remote installer: ${installer_url}" >&2
 		exit 1
 	fi
 
diff --git a/bin/rpi-prep b/bin/rpi-prep
--- a/bin/rpi-prep
+++ b/bin/rpi-prep
@@ -10,7 +10,7 @@ function out()
 	umount_all
 
 	if [ "${rc}" -ne 0 ] ; then
-        echo "-- Script failed" >&2
+        echo "** Error: Script failed" >&2
     fi
 }
 
@@ -68,7 +68,7 @@ while [ "${#}" -gt 0 ] ; do
 			elif [ -z "${installer}" ] ; then
 				installer=${1}
 			else
-				echo "-- Invalid argument: ${1}" >&2
+				echo "** Error: Invalid argument: ${1}" >&2
 				exit 2
 			fi
 			;;
@@ -82,12 +82,12 @@ if [ -z "${image}" ] ; then
 fi
 
 if ! [ -e "${image}" ] ; then
-	echo "No such image file: ${image}" >&2
+	echo "** Error: No such image file: ${image}" >&2
 	exit 1
 fi
 
 if [ -n "${installer}" ] && ! [ -e "${installer}" ] ; then
-	echo "No such installer: ${installer}" >&2
+	echo "** Error: No such installer: ${installer}" >&2
 	exit 1
 fi
 
@@ -103,7 +103,7 @@ case "${image}" in
 		# Check the number of files in the zipped image
 		num_files=$(zipinfo -1 "${image}" | wc -l)
 		if [ "${num_files}" -ne 1 ] ; then
-			echo "-- Invalid number of zipped files: ${num_files}" >&2
+			echo "** Error: Invalid number of zipped files: ${num_files}" >&2
 			exit 1
 		fi
 		echo "-- Unzip image"
@@ -114,7 +114,7 @@ case "${image}" in
 		cp "${image}" "${outfile}"
 		;;
 	*)
-		echo "-- Unsupported image file format" >&2
+		echo "** Error: Unsupported image file format" >&2
 		exit 1
 		;;
 esac
@@ -137,13 +137,13 @@ elif  [ "${num_parts}" -eq 2 ] ; then
 	elif [ -d "${ROOT_DIR}"/boot ] ; then
 		boot_dir=${ROOT_DIR}/boot
 	else
-		echo "-- No such boot directory: ${ROOT_DIR}/boot{/firmware,}" >&2
+		echo "** Error: No such boot directory: ${ROOT_DIR}/boot{/firmware,}" >&2
 		exit 1
 	fi
 	BOOT_DIR=$(partmount -s "${outfile}" 1 "${boot_dir}")
 	echo "-- Image partitions mounted on ${ROOT_DIR}"
 else
-	echo "-- Unsupported number of partitions: ${num_parts}" >&2
+	echo "** Error: Unsupported number of partitions: ${num_parts}" >&2
 	exit 1
 fi
 
