rpi-install: Update ourselves
Signed-off-by: Juerg Haefliger <juergh@canonical.com>

diff --git a/bin/rpi-install b/bin/rpi-install
--- a/bin/rpi-install
+++ b/bin/rpi-install
@@ -103,16 +103,16 @@ if [ -n "${installer}" ] ; then
 
 else
 	# Check if the remote installer exists
-	installer_url=${github_url}/raw/main/release/rpi-install.tgz
-	if ! wget -q --spider "${installer_url}" ; then
-		echo "** Error: No such remote installer: ${installer_url}" >&2
+	url=${github_url}/raw/main/release/rpi-install.tgz
+	if ! wget -q --spider "${url}" ; then
+		echo "** Error: No such remote file: ${url}" >&2
 		exit 1
 	fi
 
 	# Download and unpack the installer
 	rm -rf "${boot_dir}/install"
-	echo "-- Install ${installer_url}"
-	wget -q -O - "${installer_url}" | tar -C "${boot_dir}" -xzf -
+	echo "-- Install ${url}"
+	wget -q -O - "${url}" | tar -C "${boot_dir}" -xzf -
 fi
 
 # Modify config.txt
@@ -127,3 +127,18 @@ cat << EOF >> "${boot_dir}"/config.txt
 include install/config.txt
 # rpi-install INSTALL END
 EOF
+
+# Update ourselves
+if [ -z "${installer}" ] ; then
+	url=${github_url}/raw/main/bin/rpi-install
+	if ! wget -q --spider "${url}" ; then
+		echo "** Error: No such remote file: ${url}" >&2
+		exit 1
+	fi
+
+	# Download ourselves
+	echo "-- Install ${url}"
+	destfile=$(which rpi-install || echo "/usr/bin/rpi-install")
+	wget -q -O "${destfile}" "${url}"
+	chmod 755 "${destfile}"
+fi
