rpi-install: Bail out if an invalid argument is provided
Signed-off-by: Juerg Haefliger <juergh@canonical.com>

diff --git a/bin/rpi-install b/bin/rpi-install
--- a/bin/rpi-install
+++ b/bin/rpi-install
@@ -48,6 +48,10 @@ while [ "${#}" -gt 0 ] ; do
 		-r|--reboot)
 			reboot=1
 			;;
+		-*)
+			echo "-- Invalid argument: ${1}" >&2
+			exit 1
+			;;
 		*)
 			if [ -z "${installer}" ] ; then
 				installer=${1}
